# Generated by Django 5.0.7 on 2024-08-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popularpeople', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['-time_created']},
        ),
        migrations.AddIndex(
            model_name='people',
            index=models.Index(fields=['time_created'], name='popularpeop_time_cr_e82321_idx'),
        ),
    ]
