# Generated by Django 5.0.7 on 2024-08-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popularpeople', '0003_people_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
