# Generated by Django 5.0.7 on 2024-08-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popularpeople', '0005_alter_people_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Draft Article'), (1, 'Actual Article')], default=1),
        ),
    ]
