# Generated by Django 5.0.7 on 2024-08-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popularpeople', '0010_partner_people_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
