# Generated by Django 5.0.7 on 2024-08-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popularpeople', '0012_uploadfiles_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%d/%m/%Y/', verbose_name='Photo'),
        ),
    ]
