# Generated by Django 5.0.7 on 2024-08-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popularpeople', '0013_people_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['-time_created'], 'verbose_name': 'Popular People', 'verbose_name_plural': 'Popular People'},
        ),
        migrations.AlterField(
            model_name='people',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/', verbose_name='Photo'),
        ),
    ]
